[package]
name = "broodrep-cli"
version = "0.2.0"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/ShieldBattery/broodrep"

[dependencies]
broodrep = { path = "../broodrep" }
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"
